#!/bin/bash
# Waveshare AI firmware: host tests + ESP-IDF build (+ optional flash).
#   NO_FLASH=1 ./dev.sh                  host tests + build only (no serial port is opened)
#   ./dev.sh                             ... then flash + monitor the single Espressif USB device
#   PORT=/dev/cu.usbmodemXXXX ./dev.sh   choose the port explicitly
#   PROVIDERS=hermes,home_assistant NO_FLASH=1 ./dev.sh   build these providers for one run (hermes,
#                                        home_assistant, or none = the device core only); overrides
#                                        WAVESHARE_AI_PROVIDERS in .env
# Your board's device settings come from the git-ignored .env (see .env.example): WAVESHARE_AI_PROVIDERS,
# WAVESHARE_AI_HERMES_TILES, WAVESHARE_AI_HERMES_ACCOUNT_NAME, WAVESHARE_AI_HOME_ASSISTANT_ACCOUNT_NAME and
# WAVESHARE_AI_AUTO_SLEEP_MIN. dev.sh reads only those keys (tools/local_config.sh); the Wi-Fi lines are for
# tools/set_wifi.py and never enter the build. Any of them set -> one generated
# devices/waveshare-esp32-s3-touch-amoled-1-8-v2/firmware/build/device.defaults and
# sdkconfig.device; none set -> the plain default build.
# Required toolchain (see docs/SETUP.md): ESP-IDF 6.0.x and its Python env, nothing else.
#   IDF_PATH            ESP-IDF 6.0.x checkout (default: ../esp-idf-6.0.2 next to this repo)
set -euo pipefail
ROOT="$(cd "$(dirname "$0")" && pwd)"
: "${HOME:?HOME must be set}"
source "$ROOT/tools/local_config.sh"
# Device settings (.env, PROVIDERS=), checked before anything slow.
FIRMWARE="$ROOT/devices/waveshare-esp32-s3-touch-amoled-1-8-v2/firmware"
DEVICE_DEFAULTS="$(local_config_device_defaults "$ROOT/.env" "${PROVIDERS:-}")" || exit 2
export IDF_PATH="${IDF_PATH:-$ROOT/../esp-idf-6.0.2}"
[[ -f "$IDF_PATH/export.sh" ]] || { echo "Set IDF_PATH to an ESP-IDF 6.0.x checkout" >&2; exit 2; }
printf '%s\n' 'Running host C suites (ASan/UBSan)'
"$ROOT/tests/run_host_tests.sh"
# Prefer an already provisioned IDF Python, independent of the system default.
if [[ -z "${IDF_PYTHON_ENV_PATH:-}" ]]; then
  for env in "$HOME"/.espressif/python_env/idf6.0_py3.*_env; do
    [[ -x "$env/bin/python" ]] && export IDF_PYTHON_ENV_PATH="$env" && break
  done
fi
set +u  # IDF export scripts are not nounset-compatible.
source "$IDF_PATH/export.sh" >/dev/null
set -u
cd "$FIRMWARE"
# Always explicit, so a later default build does not inherit device settings from the CMake cache.
PRESET=(-DSDKCONFIG="$FIRMWARE/sdkconfig" -DSDKCONFIG_DEFAULTS="sdkconfig.defaults")
if [[ -n "$DEVICE_DEFAULTS" ]]; then
  # Your device settings get one generated sdkconfig inside the git-ignored build dir, so they never
  # edit the default device sdkconfig and switching back is just a run without them. It is
  # regenerated whenever device.defaults changes (e.g. a new label in .env).
  mkdir -p "$FIRMWARE/build"
  printf '# Generated by dev.sh from .env / PROVIDERS= (see .env.example). Do not edit.\n%s\n' "$DEVICE_DEFAULTS" \
    >"$FIRMWARE/build/device.defaults"
  local_config_fresh "$FIRMWARE/build/sdkconfig.device" "sdkconfig.defaults;build/device.defaults"
  PRESET=(-DSDKCONFIG="$FIRMWARE/build/sdkconfig.device" -DSDKCONFIG_DEFAULTS="sdkconfig.defaults;build/device.defaults")
fi
idf.py "${PRESET[@]+"${PRESET[@]}"}" -DIDF_TARGET=esp32s3 -DVOICE_SELFTEST="${VOICE_SELFTEST:-OFF}" build
if [[ "${NO_FLASH:-0}" == 1 ]]; then
  printf '%s\n' 'NO_FLASH=1: build complete; no port enumeration, flash, or monitor'
  exit 0
fi
MONITOR="${MONITOR:-1}" "$ROOT/tools/flash.sh"
