#!/usr/bin/env python3
"""Offline, deterministic SVG -> 192px alpha masks. Requires ImageMagick 7.1.2-15.
Original Google SVGs remain byte-identical; no runtime font/network dependency.
"""
import argparse
import hashlib
import json
from pathlib import Path
import subprocess

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / 'assets/material-symbols'
OUT = ROOT / 'devices/waveshare-esp32-s3-touch-amoled-1-8-v2/firmware/main/material_symbols.h'

def generate():
    provenance = json.loads((ASSETS / 'provenance.json').read_text())
    version = subprocess.check_output(['magick', '-version'], text=True).splitlines()[0]
    if 'ImageMagick 7.1.2-15 Q16-HDRI' not in version:
        raise SystemExit('Pinned converter required: ImageMagick 7.1.2-15 Q16-HDRI')
    lines = ['/* Generated by tools/generate_material_symbols.py; Google Material Symbols',
             ' * Rounded, Apache-2.0: assets/material-symbols/LICENSE and provenance.json. */',
             '#pragma once', '#include <stdint.h>', '#define MATERIAL_SIZE 192']
    for name in ('auto_awesome', 'mic', 'settings', 'sensors'):
        source = ASSETS / (name + '.svg')
        assert hashlib.sha256(source.read_bytes()).hexdigest() == provenance['files'][source.name]['sha256']
        alpha = subprocess.check_output(['magick', '-background', 'none', '-density', '1152', str(source),
                '-resize', '192x192!', '-alpha', 'extract', '-depth', '8', 'gray:-'])
        assert len(alpha) == 192 * 192
        # Translate the actual ink bounds to the panel's half-pixel center.
        xs = [i % 192 for i, a in enumerate(alpha) if a]
        ys = [i // 192 for i, a in enumerate(alpha) if a]
        dx = (191 - min(xs) - max(xs)) // 2
        dy = (191 - min(ys) - max(ys)) // 2
        centered = bytearray(len(alpha))
        for i, a in enumerate(alpha):
            x, y = i % 192 + dx, i // 192 + dy
            if a:
                assert 0 <= x < 192 and 0 <= y < 192
                centered[y * 192 + x] = a
        lines.append('static const uint8_t material_' + name + '[MATERIAL_SIZE*MATERIAL_SIZE]={')
        lines.extend(','.join(str(a) for a in centered[i:i+32]) + ',' for i in range(0,len(centered),32))
        lines.append('};')
    return '\n'.join(lines) + '\n'

if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    result = generate()
    if args.check:
        assert OUT.read_text() == result, 'Generated assets differ'
        print('Material Symbols source hashes and reproducible header: PASS')
    else:
        OUT.write_text(result)
